language: python
python:
  - "2.7"
install:
  - "pip install -r deps/core.txt"
  - "pip install -r deps/test.txt"
script:
  - "nosetests"
after_success:
  - "coveralls"

branches:
  only:
    - master
    - dev
