language: python
python:
  - "2.7"
  - "2.6"
install:
  - "pip install -r req.txt"
  - "pip install -r req-test.txt"
script:
  - "flake8 pylease"
  - "flake8 tests"
  - "nosetests"

branches:
  only:
    - master
    - dev